version: '2'
services:
    resume-app:
        image: resume
        external_links:
            - resume-mysql:mysql
            - resume-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/resume?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    resume-mysql:
        extends:
            file: mysql.yml
            service: resume-mysql
    resume-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: resume-elasticsearch
